### ISSUE TITLE
[Group creation] Design user interface

### ISSUE THREAD

**Issue by rikyiso01** [OrangeCorporation/StudyBuds#44]
- Add input validation to ensure the following fields are not null: name, description, and telegram_link
- Implement range validation for the members limit input: the value must be greater than 2 and less than 100

**Comment by anitatehrani** [comment]
This task should be done after Figma Designs.

**Comment by anitatehrani** [comment]
These commands are needed:
D:\Orange\StudyBuds\unige>docker-compose up unigeapi
D:\Orange\StudyBuds>docker-compose up --build backend

You can run groupcreation.dart

Please test it with the emulator.
