### ISSUE TITLE
[Group creation] Get courses list integration

### ISSUE THREAD

**Issue by nomun19** [OrangeCorporation/StudyBuds#48]
The task is about fetching all courses from UNIGE mockup service by sending a request from our backend service
- the backend service should handle the request by redirecting it to the UNIGE mockup system and returning the response to the client

**Comment by anitatehrani** [comment]
This task should be done when unige mockup is ready.

**Comment by anitatehrani** [comment]
Needed Commands:
D:\Orange\StudyBuds\backend>npx ts-node server.ts
D:\Orange\StudyBuds\unige>docker-compose up unigeapi

http://localhost:5000/courses/all ----> Get the list of courses
