### ISSUE TITLE
[join group] interface

### ISSUE THREAD

**Issue by nomun19** [OrangeCorporation/StudyBuds#53]
- If a student has already sent a join request, the button text should display the status of the previous join request, and the button should be disabled
- When a student sends a join request to a public group, and the response indicates success, the join button should be hidden

**Comment by anitatehrani** [comment]
These commands are needed:
D:\Orange\StudyBuds\unige>docker-compose up unigeapi
D:\Orange\StudyBuds>docker-compose up --build backend (D:\Orange\StudyBuds\backend>npx ts-node server.ts)

[JoinRequest.json](https://github.com/user-attachments/files/17921562/JoinRequest.json)
The above file is the postman for API (http://localhost:5000/groups/join).

You can get the list of join requests by the below URL:
http://localhost:5000/groups/join-requests
