### ISSUE TITLE
[Group details] API

### ISSUE THREAD

**Issue by rikyiso01** [OrangeCorporation/StudyBuds#90]
The backend task for receiving request from frontend and it returns group detailed information. 
response data includes all group members' studentId and group name, description, type, telegram link, current group member's number, and group member limit.

**Comment by nomun19** [comment]
the group detail information has to include groupId, course, members, studentId, name, lastname. I guess response might be like {groupId, name, description, isPublic, telegramLink, studentId(this id is admin student's id),  members(this is current members number), groupMembers: [{studentId, firstname, lastname},..].

groupMembers has to be list of object that object includes the studentId, firstName, lastName. 

when you get students' name and lastName, you should send request to unigemockup. There is one new api that receive studentId's list, it'll  return [{studentId, firstname, lastname}] formatted object list. The api's path is "/students", you should write function on the unige_service.ts file. 

@anitatehrani  @AkimbetovaAyaulym

**Comment by anitatehrani** [comment]
http://localhost:5000/groups/group_details/{group_id}
